// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login in to account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login in to account",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Logged in",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Create room",
                "parameters": [
                    {
                        "description": "room",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomCreatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new room",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get room list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Get room list",
                "responses": {
                    "201": {
                        "description": "rooms",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomListRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room/update": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Update room",
                "parameters": [
                    {
                        "description": "room",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Updated room",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room/{room_id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get room by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Get room by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "room_id",
                        "name": "room_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "room",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "Delete room",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "room_id",
                        "name": "room_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Room",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room_type/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create roomType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomType"
                ],
                "summary": "Create roomType",
                "parameters": [
                    {
                        "description": "roomType",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeCreatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new roomType",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room_type/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get roomType list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomType"
                ],
                "summary": "Get roomType list",
                "responses": {
                    "201": {
                        "description": "room_types",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeListRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room_type/update": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update roomType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomType"
                ],
                "summary": "Update roomType",
                "parameters": [
                    {
                        "description": "roomType",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Updated roomType",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/room_type/{room_type_id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get roomType by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomType"
                ],
                "summary": "Get roomType by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "room_type_id",
                        "name": "room_type_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "roomType",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomTypeSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete roomType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomType"
                ],
                "summary": "Delete roomType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "room_type_id",
                        "name": "room_type_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "RoomType",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/student/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Create student",
                "parameters": [
                    {
                        "description": "student",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.StudentCreatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new student",
                        "schema": {
                            "$ref": "#/definitions/domain.StudentSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/student/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get student list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Get student list student",
                "responses": {
                    "201": {
                        "description": "student",
                        "schema": {
                            "$ref": "#/definitions/domain.StudentListRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/student/update": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Update student",
                "parameters": [
                    {
                        "description": "student",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.StudentUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Updated student",
                        "schema": {
                            "$ref": "#/definitions/domain.StudentSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/student/{student_id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get student by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Get student by id student",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student_id",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "student",
                        "schema": {
                            "$ref": "#/definitions/domain.StudentSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "Delete student",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student_id",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "student",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/subject/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create subject",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Create subject",
                "parameters": [
                    {
                        "description": "subject",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateSubjectPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new subject",
                        "schema": {
                            "$ref": "#/definitions/domain.SubjectSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/subject/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get subject list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get subject list",
                "responses": {
                    "201": {
                        "description": "subject",
                        "schema": {
                            "$ref": "#/definitions/domain.SubjectListRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/subject/update": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update subject",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Update subject",
                "parameters": [
                    {
                        "description": "subject",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateSubjectPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Updated subject",
                        "schema": {
                            "$ref": "#/definitions/domain.SubjectSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/subject/{subject_id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get subject by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get subject by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "subject",
                        "schema": {
                            "$ref": "#/definitions/domain.SubjectSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete subject",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Delete subject",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "subject_id",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "subject",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/teacher/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create teacher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teacher"
                ],
                "summary": "Create teacher",
                "parameters": [
                    {
                        "description": "teacher",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherCreatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new teacher",
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/teacher/list": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get teacher list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teacher"
                ],
                "summary": "Get teacher list teacher",
                "responses": {
                    "201": {
                        "description": "teacher",
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherListRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/teacher/update": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update teacher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teacher"
                ],
                "summary": "Update teacher",
                "parameters": [
                    {
                        "description": "teacher",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Updated teacher",
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/teacher/{teacher_id}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get teacher by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teacher"
                ],
                "summary": "Get teacher by id teacher",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "teacher_id",
                        "name": "teacher_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "teacher",
                        "schema": {
                            "$ref": "#/definitions/domain.TeacherSuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete teacher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teacher"
                ],
                "summary": "Delete teacher",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "teacher_id",
                        "name": "teacher_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "teacher",
                        "schema": {
                            "$ref": "#/definitions/domain.SuccessRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AcademicInfo": {
            "type": "object",
            "required": [
                "admission_date",
                "class_section",
                "emergency_contact",
                "grade"
            ],
            "properties": {
                "admission_date": {
                    "type": "string"
                },
                "class_section": {
                    "type": "string"
                },
                "emergency_contact": {
                    "type": "string"
                },
                "grade": {
                    "type": "string"
                },
                "prev_school": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "domain.AuthToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "domain.CreateSubjectPayload": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.EmploymentDetail": {
            "type": "object",
            "properties": {
                "conrtact_end_date": {
                    "type": "string"
                },
                "employment_type": {
                    "type": "string"
                },
                "joing_date": {
                    "type": "string"
                },
                "salary": {
                    "type": "integer"
                }
            }
        },
        "domain.LoginRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.LoginRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.AuthToken"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.Meta": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "domain.PersonalInfo": {
            "type": "object",
            "required": [
                "blood_group",
                "city",
                "date_of_birth",
                "first_name",
                "ggnder",
                "last_name",
                "phone",
                "street_address"
            ],
            "properties": {
                "blood_group": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "ggnder": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                }
            }
        },
        "domain.PersonalInformation": {
            "type": "object",
            "required": [
                "city",
                "date_of_birth",
                "first_name",
                "gender",
                "last_name",
                "phone",
                "street_address"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                }
            }
        },
        "domain.ProfessionalInformation": {
            "type": "object",
            "required": [
                "department_id",
                "qualification",
                "subject_ids",
                "teacher_id"
            ],
            "properties": {
                "department_id": {
                    "type": "integer"
                },
                "experience": {
                    "type": "integer"
                },
                "graduation_year": {
                    "type": "integer"
                },
                "qualification": {
                    "type": "string"
                },
                "subject_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "teacher_id": {
                    "type": "string"
                },
                "uni_or_ins_name": {
                    "type": "string"
                }
            }
        },
        "domain.Room": {
            "type": "object",
            "required": [
                "building_id",
                "code",
                "floor_id",
                "name",
                "room_type_id",
                "status"
            ],
            "properties": {
                "area": {
                    "type": "integer"
                },
                "building_id": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "floor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RoomCreatePayload": {
            "type": "object",
            "required": [
                "building_id",
                "code",
                "floor_id",
                "name",
                "room_type_id",
                "status"
            ],
            "properties": {
                "area": {
                    "type": "integer"
                },
                "building_id": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "floor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RoomListRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Room"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.RoomSuccessRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.Room"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.RoomType": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RoomTypeCreatePayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RoomTypeListRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RoomType"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.RoomTypeSuccessRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.RoomType"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.RoomTypeUpdatePayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.RoomUpdatePayload": {
            "type": "object",
            "required": [
                "building_id",
                "code",
                "floor_id",
                "name",
                "room_type_id",
                "status"
            ],
            "properties": {
                "area": {
                    "type": "integer"
                },
                "building_id": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "floor_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "room_type_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Student": {
            "type": "object",
            "required": [
                "academic_info",
                "personal_info"
            ],
            "properties": {
                "academic_info": {
                    "$ref": "#/definitions/domain.AcademicInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInfo"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.StudentCreatePayload": {
            "type": "object",
            "required": [
                "academic_info",
                "personal_info"
            ],
            "properties": {
                "academic_info": {
                    "$ref": "#/definitions/domain.AcademicInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInfo"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.StudentListRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Student"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.StudentSuccessRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.Student"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.StudentUpdatePayload": {
            "type": "object",
            "required": [
                "academic_info",
                "personal_info"
            ],
            "properties": {
                "academic_info": {
                    "$ref": "#/definitions/domain.AcademicInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInfo"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Subject": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.SubjectListRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Subject"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.SubjectSuccessRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.Subject"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.SuccessRes": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.Teacher": {
            "type": "object",
            "required": [
                "employment_detail",
                "personal_info",
                "professional_info"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employment_detail": {
                    "$ref": "#/definitions/domain.EmploymentDetail"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInformation"
                },
                "professional_info": {
                    "$ref": "#/definitions/domain.ProfessionalInformation"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.TeacherCreatePayload": {
            "type": "object",
            "required": [
                "employment_detail",
                "personal_info",
                "professional_info"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employment_detail": {
                    "$ref": "#/definitions/domain.EmploymentDetail"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInformation"
                },
                "professional_info": {
                    "$ref": "#/definitions/domain.ProfessionalInformation"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.TeacherListRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Teacher"
                    }
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/domain.Meta"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.TeacherSuccessRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.Teacher"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.TeacherUpdatePayload": {
            "type": "object",
            "required": [
                "employment_detail",
                "personal_info",
                "professional_info"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employment_detail": {
                    "$ref": "#/definitions/domain.EmploymentDetail"
                },
                "id": {
                    "type": "integer"
                },
                "personal_info": {
                    "$ref": "#/definitions/domain.PersonalInformation"
                },
                "professional_info": {
                    "$ref": "#/definitions/domain.ProfessionalInformation"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateSubjectPayload": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "description": "JWT security accessToken. Please add it in the format \"Bearer {AccessToken}\" to authorize your requests.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/",
	Schemes:          []string{"http", "https"},
	Title:            "School Management System API",
	Description:      "A comprehensive API for school management system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
